//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habr.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PostMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Habr.Common.Resources.PostMessageResource", typeof(PostMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post is already published.
        /// </summary>
        public static string PostAlreadyPublished {
            get {
                return ResourceManager.GetString("PostAlreadyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move a post to drafts if it has comments or rating..
        /// </summary>
        public static string PostDraftWithCommentsOrRating {
            get {
                return ResourceManager.GetString("PostDraftWithCommentsOrRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post is not found..
        /// </summary>
        public static string PostNotFound {
            get {
                return ResourceManager.GetString("PostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A published post cannot be edited. It must be moved to drafts before..
        /// </summary>
        public static string PublishedPostDelete {
            get {
                return ResourceManager.GetString("PublishedPostDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot rate your own posts..
        /// </summary>
        public static string RateOwnPostFailed {
            get {
                return ResourceManager.GetString("RateOwnPostFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must be less than {textMaxLength} symbols.\n.
        /// </summary>
        public static string TextMaxLength {
            get {
                return ResourceManager.GetString("TextMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text is required.\n.
        /// </summary>
        public static string TextRequired {
            get {
                return ResourceManager.GetString("TextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be less than {titleMaxLength} symbols.\n.
        /// </summary>
        public static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is required.\n.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
    }
}
